server:
  port: 8080

spring:
  datasource:
    username: root
    password: lai2018.
    url: jdbc:mysql://47.108.252.22/Online_Charge_Account?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.younantuiqun.onlinechargeaccount.po
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com:
      example:
        mapper: debug
#  config: classpath:log4j2.xml